# Generated by Django 3.0.4 on 2020-05-17 19:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200517_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
