# Generated by Django 3.0.4 on 2020-08-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='word_name',
            new_name='text',
        ),
    ]
