# Generated by Django 3.0.4 on 2020-06-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='owner',
        ),
    ]
