# Generated by Django 3.0.4 on 2020-08-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20200813_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='word_translation',
            new_name='translation',
        ),
    ]
