# Generated by Django 3.0.4 on 2020-06-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200520_1648'),
        ('dictionaries', '0002_remove_dictionary_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='blog_post',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogPost'),
            preserve_default=False,
        ),
    ]
