# Generated by Django 3.0.4 on 2020-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_auto_20200813_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='translation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
