# Generated by Django 3.0.4 on 2020-08-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_auto_20200813_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='blog_post',
            new_name='post_id',
        ),
    ]
